package com.wehelper.bean;


public class WhUser extends BaseBean {
	
		private Integer id;//   id	private String username;//   登录名	private String email;//   邮箱	private String password;//   登录密码	private String wh_unino_id;//   union ID	private Integer gender;//   性别	private String birthday;//   生日	private String province;//   省份	private String city;//   城市	private String country;//   国家	private String headimgurl;//   头像	private Integer state;//   状态 0=可用,1=禁用	private Integer loginCount;//   登录总次数	private java.util.Date loginTime;//   最后登录时间	private Integer superAdmin;//   是否超级管理员 0= 不是，1=是	private java.util.Date createTime;//   	private Integer createBy;//   	private java.util.Date updateTime;//   	private Integer updateBy;//   	private Integer deleted;//   	public Integer getId() {	    return this.id;	}	public void setId(Integer id) {	    this.id=id;	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getEmail() {	    return this.email;	}	public void setEmail(String email) {	    this.email=email;	}	public String getPassword() {	    return this.password;	}	public void setPassword(String password) {	    this.password=password;	}	public String getWh_unino_id() {	    return this.wh_unino_id;	}	public void setWh_unino_id(String wh_unino_id) {	    this.wh_unino_id=wh_unino_id;	}	public Integer getGender() {	    return this.gender;	}	public void setGender(Integer gender) {	    this.gender=gender;	}	public String getBirthday() {	    return this.birthday;	}	public void setBirthday(String birthday) {	    this.birthday=birthday;	}	public String getProvince() {	    return this.province;	}	public void setProvince(String province) {	    this.province=province;	}	public String getCity() {	    return this.city;	}	public void setCity(String city) {	    this.city=city;	}	public String getCountry() {	    return this.country;	}	public void setCountry(String country) {	    this.country=country;	}	public String getHeadimgurl() {	    return this.headimgurl;	}	public void setHeadimgurl(String headimgurl) {	    this.headimgurl=headimgurl;	}	public Integer getState() {	    return this.state;	}	public void setState(Integer state) {	    this.state=state;	}	public Integer getLoginCount() {	    return this.loginCount;	}	public void setLoginCount(Integer loginCount) {	    this.loginCount=loginCount;	}	public java.util.Date getLoginTime() {	    return this.loginTime;	}	public void setLoginTime(java.util.Date loginTime) {	    this.loginTime=loginTime;	}	public Integer getSuperAdmin() {	    return this.superAdmin;	}	public void setSuperAdmin(Integer superAdmin) {	    this.superAdmin=superAdmin;	}	public java.util.Date getCreateTime() {	    return this.createTime;	}	public void setCreateTime(java.util.Date createTime) {	    this.createTime=createTime;	}	public Integer getCreateBy() {	    return this.createBy;	}	public void setCreateBy(Integer createBy) {	    this.createBy=createBy;	}	public java.util.Date getUpdateTime() {	    return this.updateTime;	}	public void setUpdateTime(java.util.Date updateTime) {	    this.updateTime=updateTime;	}	public Integer getUpdateBy() {	    return this.updateBy;	}	public void setUpdateBy(Integer updateBy) {	    this.updateBy=updateBy;	}	public Integer getDeleted() {	    return this.deleted;	}	public void setDeleted(Integer deleted) {	    this.deleted=deleted;	}
}
